name: pspad
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: PSPad is a text editor for developers.
description: |
 The universal (freeware) text editor, useful for people who:

 *work with plain text - the editor has a wealth of formatting functions, including a spell checker
 *create web pages - as a web authoring editor, PSPad contains many unique tools that save your time
 *want to use a good IDE for their compiler - PSPad catches and parses compiler output, integrates external help files, compares versions and much more...

 There is no complex installation process, PSPad is ready to work immediately without requiring customization. The editor supports many file types and languages, with syntax highlighting. There are macros, clip files and templates to automate repetative tasks. Integrated HEX Editor, Project support, FTP Client, Macro Recorder, File Search/Replace, Code Explorer, Code page conversion... these are just some of the many features that PSPad offers.

confinement: strict
grade: stable
architectures:
  - build-on: amd64

plugs:
  wine-platform-plug:
    content: wine-base-stable
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform

apps:
  pspad:
    command: pspad
    desktop: usr/share/applications/pspad.desktop
    plugs: [ wayland, x11, opengl, home, desktop, desktop-legacy, network, hardware-observe, process-control, cups-control, removable-media, wine-platform-plug ]

parts:
  pspad:
    plugin: nil
    source: ./src
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget http://www.pspad.com/en/download.php -O - 2>&1 | grep current | sed 's| (|.|g;s|)||' | awk '{print $5}')
      echo $ver > $SNAPCRAFT_STAGE/version
      ./dl_psp
    stage:
      - bin
      - usr
      - wine-platform
    build-packages: [unzip,wget]
